import Head from 'next/head';

import { CardLink } from 'components/common/Link';
import * as UI from 'styles/main-page';

const cardLinkList = [
  {
    href: '/example-swr-store/count',
    h2Text: 'SWR store example',
    text: 'Find in-depth information about Next.js features and API.',
  },
  {
    href: 'example-isr-on-demand',
    h2Text: 'ISR On-demand example',
    text: 'Find in-depth information about Next.js features and API.',
  },
  {
    href: 'https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app',
    h2Text: 'Docs',
    text: 'Find in-depth information about Next.js features and API.',
    target: '_blank',
  },
  {
    href: 'https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app',
    h2Text: 'Learn',
    text: `Learn about Next.js in an interactive course with quizzes!`,
    target: '_blank',
  },
  {
    href: 'https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app',
    h2Text: 'Templates',
    text: 'Discover and deploy boilerplate example Next.js projects.',
    target: '_blank',
  },
  {
    href: 'https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app',
    h2Text: 'Deploy',
    text: 'Instantly deploy your Next.js site to a shareable URL with Vercel.',
    target: '_blank',
  },
];

const Home = () => {
  return (
    <>
      <Head>
        <title>Lanp Next App Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UI.Description>
        <UI.DescriptionP>
          Get started by editing&nbsp;
          <UI.Code>pages/index.tsx</UI.Code>
        </UI.DescriptionP>
        <div>
          <UI.DescriptionLink
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            By
            <UI.LogoVercel src="/vercel.svg" alt="Vercel Logo" width={100} height={24} priority />
          </UI.DescriptionLink>
        </div>
      </UI.Description>

      <UI.Center>
        <UI.Logo src="/next.svg" alt="Next.js Logo" width={180} height={37} priority />
        <UI.Thirteen>
          <UI.Image src="/thirteen.svg" alt="13" width={40} height={31} priority />
        </UI.Thirteen>
      </UI.Center>

      <UI.Grid>
        {cardLinkList.map(({ href, h2Text, text, target }) => (
          <CardLink key={href} href={href} h2Text={h2Text} text={text} target={target} />
        ))}
      </UI.Grid>
    </>
  );
};

export default Home;
